#make everyones messages a system message (prevents reports)
everyone_system_message: false
#force operators to have their messages replaced?
operator_forced_to_use: false
#auto add ops to the replace list on join?
operator_add_to_list_on_join: true
#people with this permission will have thier messages replaced
replace_permission: "btelnyy.replacemessages"
#should people with the above permission be automatically added to the message replace list?
permission_add_to_list_on_join: true