# Language File
#   The file is found from /plugins/btelnyy-nochatreport/
lang_file: "language.yml"

# Make everyone's messages a system message (prevents reports)
everyone_system_message: true

# Force operators to have their messages replaced?
operator_forced_to_use: false

# Auto add ops to the replace list on join?
operator_add_to_list_on_join: true

# Should people with the above permission be automatically added to the message replace list?
permission_add_to_list_on_join: true

# People with this permission will have their messages replaced
replace_permission: "btelnyy.replacemessages"

# People with this permission cannot be ignored with /ignore
no_ignore_permission: "btelnyy.noignore"

# People with this permission may view global plugin status with /ncr status
view_global_status_permission: "btelnyy.showglobalstatus"

# People with this permission may disable or enable to the plugin globally with /ncr <enable|disable>
change_global_status_permission: "btelnyy.changeglobalstatus"

# Use a different replace method? (This would work better with DiscordSRV)
use_alternative_replace_method: false