name: btelnyy-nochatreport
main: me.btelnyy.nochatreport.NoChatReport
version: ${project.version}
api-version: 1.19
commands:
   nochatreport:
      description: Change your messages to system messages to remove reports
      usage: /nochatreport
      permission: btelnyy.command.nochatreport
   msg:
      description: Message another user without them being able to report you
      usage: /msg <player> <message>
      permission: btelnyy.command.msg
   me: 
      description: Like the vanilla /me command
      usage: /me <action>
      permission: btelnyy.command.me